.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH 4PANE 1 "October 27, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
4Pane \- a detailed\-view quad\-pane gui file manager
.SH SYNOPSIS
.B 4Pane
[\-d <str>] [\-c <str>] [\-h] [Display from this filepath (optional)...]
.br

.SH DESCRIPTION
This manual page documents only 4Pane\'s rarely\-used invocation options (generally you'll just type '4Pane').
.br
A detailed manual is available from within 4Pane, either from the help menu or by pressing F1; and also online at http://4pane.co.uk
.PP
.SH OPTIONS
.TP
.B  \-d, \-\-home\-dir=<str>
Use <str> as the home directory (optional)
.TP
.B  \-c, \-\-config\-fpath=<str>
Use this filepath as 4Pane's configuration file (optional. If the filepath doesn't exist, it will be created)
.TP
.B \-h, \-\-help
Show a summary of options
.br
.SH AUTHOR
4Pane was written by David Hart <david@4pane.co.uk>.
.PP
This manual page was written by David Hart <david@4pane.co.uk>,
(but may be used by others).
